version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-backend
    container_name: go-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
